server:
  port: 8088

spring:
  application:
    name: knowbase-app
  datasource:
    url: jdbc:postgresql://localhost:5433/knowbase
    username: knowbase
    password: knowbase
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

knowbase:
  enabled: true
  web:
    exposed: true
  tenant:
    default-tenant-id: default
  persistence:
    enabled: true
  ollama:
    enabled: true
    base-url: http://localhost:11434
    embedding-model: bge-m3
    chat-model: llama3.2
    embedding-dimension: 1024
    timeout: 60s
  upload:
    max-file-size-bytes: 209715200   # 200MB
    max-files-per-batch: 50
  storage:
# 本地FS存储系统，默认本地文件系统对象存储根目录
#    type: local
#    local-root: D:\data\knowbase-storage
    type: minio
    default-bucket: knowbase
    minio:
      endpoint: http://192.168.14.65:9000
      access-key: minioadmin
      secret-key: minioadmin
      auto-create-bucket: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn
